---
- name: Create a basic ssh_key
  hetzner.hcloud.hcloud_ssh_key:
    api_token: "{{ lookup('env','HCLOUD_TOKEN') | default(hetzner_token, true) }}"
    name: "{{ key_name }}"
    public_key: "{{ pub_key }}"
    state: "{{ hetzner_server_state }}"

- name: build list of workers
  debug:
    msg: "{{ node_name }}-{{ item }}"
  loop: "{{ range(0, hetzner_worker_count)|list }}"
  register: workernames

- name: set worker list fact
  set_fact:
    workernames: "{{ workernames.results | map(attribute='msg') | list }}"

- name: master count can't be divisibleby 2
  assert:
    that: hetzner_master_count |int is not divisibleby 2

- name: build list of masters
  debug:
    msg: "{{ master_name }}-{{ item }}"
  loop: "{{ range(0, hetzner_master_count)|list }}"
  register: masternames

- name: set master list fact
  set_fact:
    masternames: "{{ masternames.results | map(attribute='msg') | list }}"

#- name: build list of etcd
#  debug:
#    msg: "etcd{{ item }}"
#  loop: "{{ range(0, hetzner_master_count)|list }}"
#  register: etcdcount

#- name: set master list fact
#  set_fact:
#    etcdcount: "{{ etcdcount.results | map(attribute='msg') | list }}"

- name: execute hcloud deployment master
  module_defaults:
    hetzner.hcloud.hcloud_server:
      api_token: "{{ lookup('env','HCLOUD_TOKEN') | default(hetzner_token, true) }}"
      image: "{{ hetzner_instance_os }}"
      server_type: "{{ hetzner_instance_type_m }}"
      #labels:
      #  master: ""
      ssh_keys: "{{ hetzner_ssh_keys }}"
      state: "{{ hetzner_server_state }}"
  block:
    - with_together:
       - "{{ masternames }}"
       #- "{{ etcdcount }}"
      hetzner.hcloud.hcloud_server:
        name: "{{ item.0 }}"
        labels:
          master: ""
          #etcd: "{{ item.1 }}"
      register: hcloud_server_master

- name: execute hcloud deployment worker
  module_defaults:
    hetzner.hcloud.hcloud_server:
      api_token: "{{ lookup('env','HCLOUD_TOKEN') | default(hetzner_token, true) }}"
      image: "{{ hetzner_instance_os }}"
      server_type: "{{ hetzner_instance_type_w }}"
      labels:
        worker: ""
      ssh_keys: "{{ hetzner_ssh_keys }}"
      state: "{{ hetzner_server_state }}"
  block:
    - loop: "{{ workernames }}"
      hetzner.hcloud.hcloud_server:
        name: "{{ item }}"
      register: hcloud_server_worker

- name: execute hcloud server network
  module_defaults:
    hetzner.hcloud.hcloud_server_network:
      api_token: "{{ lookup('env','HCLOUD_TOKEN') | default(hetzner_token, true) }}"
      network: "{{ hetzner_network_name }}"
      state: "{{ hetzner_server_state }}"
  block:
    - loop: "{{ masternames + workernames }}"
      hetzner.hcloud.hcloud_server_network:
        server: "{{ item }}"
  when:
    - ( hcloud_server_master.results[0].hcloud_server.status is defined ) or
      ( hcloud_server_worker.results[0].hcloud_server.status is defined )
